export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const TOKEN_UPDATED = "TOKEN_UPDATED";

export const LOGOUT = "LOGOUT";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";

export const RECIPE = "RECIPE"
export const RECIPE_PENDING = 'RECIPE_PENDING';
export const RECIPE_FULFILLED = 'RECIPE_FULFILLED';
export const RECIPE_REJECTED = 'RECIPE_REJECTED';
export const SET_CURRENT = 'SET_CURRENT';

export const TOGGLE_QUICK_ACTIONS = "TOGGLE_QUICK_ACTIONS";

export const USER = "USER";
export const USER_PENDING = "USER_PENDING";
export const USER_FULFILLED = "USER_FULFILLED";
export const USER_REJECTED = "USER_REJECTED";
export const USER_UPDATE = "USER_UPDATE";
